// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package packagemanager

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackageManager *string  `mapstructure:"package_manager" required:"false" cty:"package_manager" hcl:"package_manager"`
	Update         *bool    `mapstructure:"update" required:"false" cty:"update" hcl:"update"`
	Upgrade        *bool    `mapstructure:"upgrade" required:"false" cty:"upgrade" hcl:"upgrade"`
	Packages       []string `mapstructure:"packages" required:"false" cty:"packages" hcl:"packages"`
	CleanCache     *bool    `mapstructure:"clean_cache" required:"false" cty:"clean_cache" hcl:"clean_cache"`
	Verify         *bool    `mapstructure:"verify" required:"false" cty:"verify" hcl:"verify"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"package_manager": &hcldec.AttrSpec{Name: "package_manager", Type: cty.String, Required: false},
		"update":          &hcldec.AttrSpec{Name: "update", Type: cty.Bool, Required: false},
		"upgrade":         &hcldec.AttrSpec{Name: "upgrade", Type: cty.Bool, Required: false},
		"packages":        &hcldec.AttrSpec{Name: "packages", Type: cty.List(cty.String), Required: false},
		"clean_cache":     &hcldec.AttrSpec{Name: "clean_cache", Type: cty.Bool, Required: false},
		"verify":          &hcldec.AttrSpec{Name: "verify", Type: cty.Bool, Required: false},
	}
	return s
}
